# -*- coding: utf-8 -*-
"""visualization-project-laptop-defects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eDgY_GAbYTh-3lIp4VI6c1bMQIXmZDfT
"""

import pandas as pd
import matplotlib.pyplot as plt

"""###1 What is target market? Male or female? (more frequent buyer)"""

data = pd.read_excel('/content/Data_Analysis_Project.xlsx', sheet_name='Data')
data

"""#1"""

data["Month"] = pd.to_datetime(data["Month ID(YYYYMM)"], format="%Y%m")
data

data1 = data.plot("Month", "Defects", marker="o")

"""#2"""

data2 = data.plot("Month", "Opportunities", marker="o")

"""#3"""

limit_2std = pd.Series(limit_2std)
limit_3std = pd.Series(limit_3std)

limit_2std = limit_2std.iloc[0]
limit_3std = limit_3std.iloc[0]

data3 = plt.plot(data.index, defect_rate, marker='o', linestyle='-', color='blue', label = 'Defect Rate')
plt.axhline(y=mean_defect_rate, color ='r', linestyle='--', label='Mean Defect Rate')
plt.axhline(y=limit_2std, color='purple', linestyle='--', label='UCL (Mean + 3σ)')
plt.axhline(y=limit_3std, color='red', linestyle='--', label='UCL (Mean - 3σ)')
plt.title('Defect Rate with limits')
plt.xlabel('Time')
plt.ylabel('Defect Rate')
plt.legend()

limit_2std = limit_2std.iloc[0]
limit_3std = limit_3std.iloc[0]

data3 = plt.plot(data.index, defect_rate, marker='o', linestyle='-', color='blue', label = 'Defect Rate')
plt.axhline(y=mean_defect_rate, color ='r', linestyle='--', label='Mean Defect Rate')
plt.axhline(y=limit_2std, color='purple', linestyle='--', label='UCL (Mean + 3σ)')
plt.axhline(y=limit_3std, color='red', linestyle='--', label='UCL (Mean - 3σ)')
plt.title('Defect Rate with limits')
plt.xlabel('Time')
plt.ylabel('Defect Rate')
plt.legend()
data.plot("Month", "Defects", marker="o")
data.plot("Month", "Opportunities", marker="o")
plt.show()

"""##The first graph shows us that the defects in laptops increases over time.

##The second shows us similar data for opportunities. There is a drastic increase as the months pass, but the increase in opportunities is larger than that of the defects.

##The third shows us the same data in graphs one and two, but with the mean of the defects on top of them. The large spike in the beginning, affects the mean of defects, as the mean in slightly higher than most observations as the months pass.
"""